# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AeMbAD6Xh4hohTc7NLLXoXMGGOxXWBOr
"""

import streamlit as st
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow.keras.datasets import mnist
import random
import matplotlib.pyplot as plt

# Load model and dataset
model = load_model('digit_generator_model.h5')
(_, _), (x_test, y_test) = mnist.load_data()
x_test = x_test / 255.0

# App interface
st.title("🧠 Handwritten Digit Generator")
digit = st.selectbox("Select a digit (0-9):", list(range(10)))
generate = st.button("Generate 5 Images")

if generate:
    # Filter all images of selected digit
    digit_images = x_test[y_test == digit]
    selected_images = random.sample(list(digit_images), 5)

    st.subheader(f"Generated images for digit: {digit}")
    cols = st.columns(5)
    for i in range(5):
        with cols[i]:
            st.image(selected_images[i], width=80, clamp=True, channels="L")